"""projects fix

Revision ID: a7df0fb38ca5
Revises: 699aa68d72d6
Create Date: 2026-02-09 14:16:30.006728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a7df0fb38ca5'
down_revision = '699aa68d72d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_id'), table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    # ### end Alembic commands ###
