
name: Build Docker Images and Push to GitHub Registry

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish
        run: |
          docker login --username mauricekoster --password ${{ secrets.GH_TOKEN }} ghcr.io
          docker build backend/ -t ghcr.io/mauricekoster/testdashboard-backend:latest
          docker build frontend/ -t ghcr.io/mauricekoster/testdashboard-frontend:latest
          docker push ghcr.io/mauricekoster/testdashboard-backend:latest
          docker push ghcr.io/mauricekoster/testdashboard-frontend:latest
